version: "3"
services:
  redis:
    container_name: redis
    image: docker.io/redis
    ports:
      - "6379:6379"

  redis-benchmark:
    container_name: redis-benchmark
    image: docker.io/redis
    entrypoint: redis-benchmark
    command: "-h redis -p 6379"