version: "3"
services:
  redis:
    container_name: redis
    image: docker.io/redis
    ports:
      - "6379:6379"

  redis-benchmark:
    container_name: redis-benchmark
    image: docker.io/redis
    entrypoint: redis-benchmark
    command: "-h redis -p 6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: docker.io/rediscommander/redis-commander:latest
    ##build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8080:8081"  